name: gnome-recipes
adopt-info: gnome-recipes
base: core22
summary: GNOME loves to cook
description: |
  Recipes is an easy-to-use application that will help you to discover what to cook
  today, tomorrow, the rest of the week and for your special occasions.

  Recipes comes with a collection of recipes that have been collected by GNOME contributors
  from all over the world. It also lets you store your own recipes and share them with your
  friends.

  The major features of Recipes include:
    * Add and edit your own recipes
    * Share recipes with your friends
    * Export and print shopping lists
    * Adjust quantities based on the number of servings
    * Mark recipes to cook later or add them to your favorites
    * Add notes to recipes
    * Hands-free cooking instruction mode

  An easy-to-use application that will help you to discover what to cook
  today, tomorrow, the rest of the week and for your special occasions.

grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
  gnome-recipes:
    interface: dbus
    bus: session
    name: org.gnome.Recipes

apps:
  gnome-recipes:
    extensions: [gnome]
    command: usr/bin/gnome-recipes
    #plugs:
    #  - mount-observe
    #  - calendar-service

parts:
  gnome-online-accounts:
    source: https://gitlab.gnome.org/GNOME/gnome-online-accounts
    source-type: git
    source-tag: '3.45.2'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    build-packages:
      - cmake
      - libjavascriptcoregtk-4.1-dev
      - libkrb5-dev

  gnome-recipes:
    after: [gnome-online-accounts]
    source: https://github.com/GNOME/recipes.git
    source-type: git
    source-tag: '2.0.4'
    plugin: meson
    parse-info: [usr/share/metainfo/org.gnome.Recipes.appdata.xml]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    build-packages:
      - libgnome-autoar-0-dev
      - libwebkit2gtk-4.1-dev
    stage-packages:
      - libgnome-autoar-0-0
      - libwebkit2gtk-4.1-0


  cleanup:
    after: [ gnome-recipes ]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
      # remove cross-installed repeated libraries (in /usr/lib in the SDK, but in /usr/lib/TRIPLET
      # here, and the opposite)
      for snap in "core22" "gnome-42-2204"; do
        cd "/snap/$snap/current/usr/lib"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET/$filename"
        done
        cd "/snap/$snap/current/usr/lib/$CRAFT_ARCH_TRIPLET"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$filename"
        done
      done
