name: gnome-recipes
adopt-info: gnome-recipes
base: core24
summary: GNOME loves to cook
description: |
  Recipes is an easy-to-use application that will help you to discover what to cook
  today, tomorrow, the rest of the week and for your special occasions.

  Recipes comes with a collection of recipes that have been collected by GNOME contributors
  from all over the world. It also lets you store your own recipes and share them with your
  friends.

  The major features of Recipes include:
    * Add and edit your own recipes
    * Share recipes with your friends
    * Export and print shopping lists
    * Adjust quantities based on the number of servings
    * Mark recipes to cook later or add them to your favorites
    * Add notes to recipes
    * Hands-free cooking instruction mode

  An easy-to-use application that will help you to discover what to cook
  today, tomorrow, the rest of the week and for your special occasions.

grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
  gnome-recipes:
    interface: dbus
    bus: session
    name: org.gnome.Recipes

apps:
  gnome-recipes:
    extensions: [gnome]
    command: usr/bin/gnome-recipes
    desktop: usr/share/applications/org.gnome.Recipes.desktop
    #plugs:
    #  - mount-observe
    #  - calendar-service

parts:
  librest:
    source: https://gitlab.gnome.org/GNOME/librest.git
    source-tag: '0.8.1'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     same-major: true
#     same-minor: true
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=\${exec_prefix}/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    build-packages:
      - gtk-doc-tools
      - libsoup2.4-dev
      - libsoup-gnome2.4-dev
    stage-packages:
      - libsoup-2.4-1
      - libsoup-gnome-2.4-1

  gnome-recipes:
    after: [librest]
    source: https://github.com/GNOME/recipes.git
    source-type: git
    source-tag: '2.0.4'
    source-depth: 1
    plugin: meson
    parse-info: [usr/share/metainfo/org.gnome.Recipes.appdata.xml]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    build-packages:
      - libgnome-autoar-0-dev
      - libsoup2.4-dev
      - libsoup-gnome2.4-dev
      - librest-dev
      - libgoa-1.0-dev
    stage-packages:
      - libgnome-autoar-0-0
      - libsoup-2.4-1
      - libsoup-gnome-2.4-1
      - librest-1.0-0
      - libgoa-1.0-0b
    build-snaps:
      - gnome-46-2404-sdk/latest/candidate

  cleanup:
    after: [ gnome-recipes ]
    plugin: nil
    build-snaps: [core24, gtk-common-themes, gnome-46-2404/latest/candidate]
    override-prime: |
      set -eux
      for snap in "core24" "gtk-common-themes" "gnome-46-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
      # remove cross-installed repeated libraries (in /usr/lib in the SDK, but in /usr/lib/TRIPLET
      # here, and the opposite)
      for snap in "core24" "gnome-46-2404"; do
        cd "/snap/$snap/current/usr/lib"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET/$filename"
        done
        cd "/snap/$snap/current/usr/lib/$CRAFT_ARCH_TRIPLET"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$filename"
        done
      done
